/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ejercicio4;

public class App {
    public int mejorBeneficio(int[][] entrada, int combustible) {
        int k = entrada.length;
        for (int i = 0; i < k; i++) {
            
        }
        return 1;
    }
}
