/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ejercicio1;

public class App {
    static public int[] algoritmoVoraz(int monto, int billetes[]) throws Exception {
        int cambio[] = new int[billetes.length];

        for (int i = 0; i < billetes.length; i++) {
            cambio[i] = 0;
        }

        for (int i = 0; i < billetes.length; i++) {
            while (billetes[i] <= monto) {
                cambio[i]++;
                monto -= billetes[i];
            }
        }

        if (monto != 0) {
            throw new Exception("El monto no se puede encontrar");
        }
        return cambio;
    }

    public static void main(String[] args) {
        int[] billetes = new int[] { 50, 25, 10, 7, 5 };
        int res[];
        try {
            res = algoritmoVoraz(121, billetes);
            for (int i = 0; i < res.length; i++) {
                System.out.println("$" + billetes[i] + ": " + res[i]);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
}
