/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ejercicio1;

public class App {
    static public int exponente(int a, int n) {
        if (n == 1) {
            return a;
        } else if (n % 2 == 0) { // n par
            return exponente(a, n / 2) ^ 2;
        } else {
            return exponente(a, (n-1)/2) ^ 2;
        }
    }

    public static int fuerzaBruta(int a, int n) {
        int res = a;
        for (int i = 0; i < n; i++) {
            res = res * a;
        }
        return res;
    }

    public static void main(String[] args) {
        System.out.println("3^2: " + exponente(3, 2));
        System.out.println("3^3: " + exponente(3, 3));
        System.out.println("3^8: " + exponente(3, 8));
        System.out.println("3^5: " + exponente(3, 5));


        // TODO  generar tabla de tiempos
    }
}
