/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package programacion1;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        assertNotNull("app should have a greeting", "app should have a greeting");
    }
}
